### ISSUE TITLE
2.1, 2.2 

### ISSUE THREAD

**Issue by tkkawa** [tkkawa/engineering#2]
## Summary
solve 2.1, 2.2 problem

## Goal
add 2.1, 2.2

## Todo
- [x] add infinite loop file
- [x] add sleep file
- [x] add print linux and Max file
- [x] add print linux and Max shell script

## Deadline
4/20

## Parent issue
None

## References
None

## Notes
None
